version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      m1-toolchain:
        patterns:
          - "tree-sitter-m1"
          - "m1-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
